import { Keyring } from "@polkadot/keyring";
import { KeyringPair } from "@polkadot/keyring/types";
import AccountType from "./constants";
export declare type DOTAccount = {
    keyring: Keyring;
    public_key: string;
    private_key?: string;
    mnemonic?: string;
    address: string;
    address_format: number;
    type: AccountType;
    source: string;
    signer: KeyringPair;
    name: string;
};
export declare function importAccount(privateKey: any, mnemonic: any, format: number, name?: string): Promise<DOTAccount>;
export declare function newAccount(): Promise<string>;
export declare function sign(): string;
export declare function getApi(): Promise<string>;
export declare function transfer(): Promise<string>;
